jotego/jtcores

1942/hdl/jt1942_mist.v
gng/hdl/jtgng_mist.v
modules/mist/jtgng_mist_base.v
modules/mist/osd.v

No need for firmware modification.
In 1942, the screen flip is immediate with the OSD, but delayed to reset with the game. I didn't want to touch the inner logic, I think you can easily fix this.
Comment: screen filter is exchanged in gng (again).

MiST: OSD with rotation

---

cores/sarms/cfg/mame2mra.toml

Default difficulty level is normal according to manual.

sarms: add default DIP settings

---

cores/cps1/cfg/mame2mra.toml

Although not mentioned in the manual, the third button allows to escape grapples.

ffight: add third button

---

cores/outrun/cfg/macros.def

I'm adding also PR to jtframe with support of line framebuffer for neptuno target
mister family targets also are compatible with mister ddr3 FB

update macros.def for neptuno, sockit, de1soc, de10standard targets

---

modules/jtframe/hdl/jtframe_board.v
modules/jtframe/hdl/video/jtframe_scan2x.v

- wraddr is incremented with alt_pix, so reset it with alt_pix, too. This fixes cores, like 1942.
- handle blank signals, and emit a scandoubled DE for HDMI usage

Scandoubler fix and handle blanks

---

cores/comsc/hdl/jtcomsc_main_decoder.v
cores/contra/hdl/jtcontra_main.v
cores/contra/hdl/jtcontra_main_decoder.v
cores/mx5k/hdl/jtmx5k_main_decoder.v

MX5K need the port_in as combinatorial, too, otherwise controls won't work.

Contra: don't delay cpu_din for Contra and variants

---

modules/jtframe/bin/jotego_20.04.sh
modules/jtframe/hdl/ver/test.cpp

When I tried jtsim -setname xxx it only worked part of the time on ubuntu 22 and never on ubuntu 20. I debugged it and found that the rm -rf frame.raw in the jtsim script was deleted before the forks creating the frame data files were finished running ImageMagick convert(). I have modified test.cpp to wait until the child processes are completed.

Avoid race condition in verilator test code

---

cores/1942/hdl/jt1942_sound.v
cores/exed/hdl/jtexed_sound.v
cores/simson/hdl/jtcolmix_053251.v

Hi, I am pleased to report that 43 cores already work with MiSTeX on a Xilinx A100T.
The core code has had excellent portability (probably because of the use of the verilator linter).
I only encountered this one minor issue: That vivado wants a begin/end block inside
verilog function declarations.
Kind regards,
Hans

fix missing begin/end in verilog functions for vivado

---

cores/fround/hdl/jt00778x.v

cores/fround/hdl/jt00778x.v: either none or all wires need to be initialized in a combined declaration

---

cores/simson/hdl/jt053246.sv
cores/simson/hdl/jtsimson_obj.v

Increased the value for ywrap to avoid the appearance of the cat-boat and the balloon from the top of the screen at the end of the first stages of both Parodius and The Simpsons

Par sprites

---

cores/riders/hdl/jtriders_colmix.v

xmen_o was being registered and used for pri1 in riders. Object priority value was delayed respect to the layers, so it made objects appearing out of frame and made priority errors between sprites and other layers (#772)

Corrected definition of object priority in riders to avoid sprite errors (#772)

---

cores/riders/hdl/jtriders_colmix.v

This fixes shadow and object not being synced in xmen.
Also, negating the shadow value that goes in the colmix fixes the colour of the images making shd_in. However, this makes shadow_in active low entering jtcolmix_053251 whereas measured in the pcb it appeared to be active high.
Maybe the signal should be negated after entering this module and not before? 
Before changes:
After:

sync of sprites and shadows in xmen

---

cores/ngpc/cfg/mame2mra.toml

Related to https://github.com/jotego/jtcores/issues/804
Display mode 0x62 (Original NGPC) was added in b89a709. This PR adds display mode 0x63 (Original NGPC+)

add NGPC+ display mode to NGPC core

---

cores/riders/hdl/jtriders_colmix.v
cores/riders/hdl/jtriders_obj.v
cores/simson/hdl/jtcolmix_053251.v

The shadow information was completely lost in the original version for taking the wrong bit
The brit value was redefined after checking again the schematics
In this version, shadows that weren't drawn by the sprite are visible, for example:
Before:
After:

Riders: brightness and shadow

---

cores/simson/hdl/jt053246_scan.sv

Due to stop registering the obj-layer in the colmix, this gap appeared again (only the left half of Wolverine is drawn with the objects):
After correction:
This also worked for vendetta/scene 6, where the anchor and part of the ship are drawn by the objects and other layer at the same time and they were not in sync before

Correction of xoffset in xmen due to not registering obj-layer anymore

---

cores/simson/hdl/jt053246_scan.sv

This change checks if the sprite starts being drawn so much to the left that it actually starts at the right end and, if so, adds a correction in the starting point.
This fixes the sentinel mouth not being correctly aligned(#765 ):

Fix for sentinel's mouth on xmen

---

cores/simson/hdl/jt053246.sv
cores/simson/hdl/jt053246_scan.sv
cores/simson/hdl/jtsimson_obj.v

Removed unused bits to simplify zoom values in k46

K46: Removed unused zoom bits

---

cores/riders/hdl/jtriders_colmix.v
cores/simson/hdl/jtcolmix_053251.v
cores/simson/hdl/jtsimson_colmix.v
cores/simson/hdl/jtsimson_obj.v
cores/tmnt/hdl/jttmnt_colmix.v
cores/xmen/hdl/jtxmen_colmix.v

Shadow priority in colmix k053251 better matching schematic logic. 
Sky and Konami logo colors are correct in The Simpsons:
Also, fixes shadows disappearing and shadow layer problems in Xmen:

Fixes #832 and some shadow issues in xmen (#765)

---

cores/riders/hdl/jt053244_scan.sv

Fixes #761 
Similar to #840, evaluating y[9] for inzone=0 made bigger sprites rejected from appearing on screen.
I removed that condition and removed the restriction of ywrap, just like how it was done in k46. 
This does not seem to interfere with #652

Removed ywrap and yw0 in k44 and redefined inzone. Fixes #761

---

cores/riders/hdl/jt053244.sv
cores/simson/hdl/jt053246.sv
cores/simson/hdl/jt053246_dma.v
cores/simson/hdl/jt053246_scan.sv
cores/simson/hdl/jtsimson_obj.v
modules/jtframe/hdl/ram/jtframe_obj_buffer.v

Managed to ensure Keep_old==0 in both simson and xmen
Reversing the order had to be made using ~ instead of -, due to priority 0 being used.
When trying to reverse the order using -, the object 0 (which previously was drawn before all other objects and never overwritten) was being overwritten due to still being drawn first, instead of last, for -0 remains unchanged. Applying ~, 0 becomes F, which would come last instead of first, overwritting everything else
SHADOW==0 had to be used in simson because Vendetta uses the shadow pen to write black pixels. With the applied conditions, in the obj buffer, these black pixels could not be drawn over something else
This change slightly helps with #841 but does not fix it completely yet:

Faster reading by reversing order also applied to Vendetta

---

cores/riders/hdl/jt053244_scan.sv

Compared the mirror logic we had for k44 (`ghf ^ pre_hf ^ hmir_eff` ) with the one in Mame. 
Both tables of truth were slightly different, so I added a small change. The pre_hflip is influenced by the horizontal mirroring, but not the other way, and that was causing the problem in #851. This commit fixes #851 
Maybe a similar approach with the vertical flip might help with #724, but I need to check it more thoroughly. I tried changing vflip definition in the same way and the scenes stayed the same

Changed horizontal mirror logic in k44. Fixes #851

---

cores/riders/hdl/jt053244_scan.sv

This change fixes #724 . Some scenes where the extra pieces of the explosion cannot be seen anymore(before/after):
Scene 26
Scene 28
When the explosion is triggered close to the bottom/top of the screen, something similar can be seen coming from the top of the screen when the explosion is at its biggest, crossing from one border of the screen to the other. However, this effect can also be found in the PCB for this circumstance:
To fix it, corrected vmir_eff evaluation, being more restrictive with the conditions and moved vscl definition to the states machine. Right after registering vzoom (state 2), calculation of the correct vscl took one more clock cycle, if vzoom remained the same, there should be no problem in state 3 for calculating vflip. However, if it did change drastically, like …

Paroda: blue bell explosion fix

---

modules/jtframe/hdl/video/jtframe_tilemap.v

It seems that this condition became reduntant from 10c77a37a1a5a55e9569e3250bfb6e538a81312b and on.
The characters/letters layer in 1942 is drawn with this module, so, when flip==1, this layer got out of the center that the rest of the layers had, as it could be seen by the top text of 1942 and Vulgus being found at the bottom (#858 , #844 )
This change fixes #858 and #844

Removed horizontal delay in jtframe_tilemap when flip==1

---

cores/s18/cfg/mame2mra.toml
cores/s18/hdl/jts18_main.v

This fixes #872 
For 2-player game, player-1 and player-2 coin positions are exchanged  in the coinage in relation to the generic configuration.
For 3 players, when "Coin chute" dip is set as "common",  only players 1 and 2 can add coins (This is what happens in MAME). For "Individual" all three coin buttons work for 3 players.
This removes `cab_1p[2]` from the `coinage` in 3-player mwalk, since it goes to `p3[3]` and having it in that position of the `coinage` leads to adding a coin for P3 whenever the start button is pressed.  
It also detects the US version of the game, since the dip switch values are switched in that version respect to the other

Detection of DIP switches in Moonwalker to enable 3-player game

---

cores/flstory/hdl/jtflstory_obj.v
cores/flstory/hdl/jtflstory_video.v

Even in flip mode (actually flip is the non-flip).

flstory: fix sprite vertical positions (#889)

---

cores/wc/cfg/mame2mra.toml
cores/wc/hdl/jtwc_game.v
cores/wc/hdl/jtwc_main.v

Fixes #887 
Also fixes weird movement in Analogue Pocket with analog controls by adapting its standard to the one used in the framework
D-pad is set as default option, while analog controls and automatic detection have to be selected in DIP switches

Added DIP switch for selecting controller type in jtwc

---

modules/jt007232/hdl/jt007232.v

This is needed to control the parameter from module instantiation (used in jtaliens, for example)

Adding missing parameter

---

cores/aliens/hdl/jtaliens_sound.v
cores/castle/hdl/jtcastle_sound.v
cores/flane/hdl/jtflane_main.v
cores/mx5k/hdl/jtmx5k_sound.v
cores/tmnt/hdl/jttmnt_sound.v
modules/jt007232/hdl/jt007232.v
modules/jt007232/hdl/jt007232_channel.v
modules/jt007232/hdl/jt007232_gain.v
modules/jt007232/ver/channel/gather.f
modules/jt007232/ver/channel/test.v
modules/jt007232/ver/gain/test.v
modules/jtframe/hdl/sound/audio_mod.yaml

As it is stated in https://github.com/jotego/jtcores/issues/910#issuecomment-2578720641, the extra zero is removed here and a test for checking the length of the channel module is added
By now, the only core where this correction has been added is in aliens.
However, I have not perceived a big difference in the pcm sound after this changed (tested in Crime Fighters only)

Removing extra zero in 007232

---

modules/jtframe/bin/jtsim

Both mem files changed their directory, so the reference in jtsim to bring them when needed was broken

Updated reference after new jtframe file layout

---

cores/simson/hdl/jtsimson_sound.v

- clear the sound RAM
- don't allow the NMI handler execute right after reset by pulling it low, so the CPU has to clear it explicitly to allow the next NMI to happen

paroda: sound fixes after reset

---

cores/outrun/cfg/msg
modules/jtframe/bin/lint-one.sh

Reduced number of characters per line in cfg/msg for fixing compilation error

minor: outrun msg

---

cores/midres/cfg/mame2mra.toml

Removing the second version, keeps the md5 the same as original.
Removed "name_sort" since it uses the same order as in cpp file

Duplicated line in toml

---

cores/roadf/cfg/mame2mra.toml

Comparing with the order used in `hyperspt.cpp`, I first used:
```
{ machine="hyperspt", name="sprites", width=16, no_offset=true, start="OBJ_START", sequence=[0,4,1,5,2,6,3,7] },
```
However, this changed the md5 code for Hyper Sports.
In the original version, even though `Name_sort=["c14","c18","c13","c17","c12","c16","c11","c15"]` is used, the created MRA states:
```
<interleave output="16">
<part name="c14" crc="c72d63be" map="01"/>
<part name="c13" crc="76565608" map="10"/>
</interleave>
<interleave output="16">
<part name="c12" crc="74d2cc69" map="01"/>
<part name="c11" crc="66cbcb4d" map="10"/>
</interleave>
<interleave output="16">
<part name="c18" crc="ed25e669" map="01"/>
<part name="c17" crc="b145b39f" map="10"/>
</interleave>
<interleave output="16">
<part name="c16" …
```

Remove name_sort from roadf TOML

---

cores/s16/hdl/jts16_fd1094_ctrl.v

s16: restrict fd1094 state change to CMPI.L #imm, Dx (#981)

---

cores/s18/cfg/mame2mra.toml

s18/lghost: sprites correctly addressed

---

modules/jtframe/bin/lint-one.sh

In the current master version, additional inputs like defining a macro or a flag are passed on to neither  `jtframe` nor `jtsim` when using `lint-one.sh`. 
The `$*` was missing when calling the functions, so I have added it

Enable additional inputs when calling lint-one.sh

---

cores/s18/cfg/mame2mra.toml

default value in MRA used to be `value="ff,fd"`

higher default difficulty in Laser Ghost

---

modules/jtframe/bin/install/jotego_20.04.sh

The installation script has been modified to be more robust in the following ways:
- You don't need to press enter when adding the `kicad` repository
- A specific version of `occt-misc` is installed before kicad to avoid issues with broken dependencies
- The generated temporary files will be removed once used
- `asm`, `verilator`, `icarus verilog`, `asl` and `mra` won't be installed if they are already installed
- To install `opbasm`, `python11` will be installed and the version requirements of `setuptools` and `wheel` will be also installed
- `jtblaster` command will be executed with sudo as needed
- You don't have to confirm the installation of `mplayer`, `audacity` and `gcc-m68k-linux-gnu`

Modified installation script to be more robust

---

cores/riders/hdl/jtglfgreat_encoder.v
cores/riders/hdl/jtriders_psac.v
cores/riders/ver/game/rest2bin.sh
cores/riders/ver/glfgreat/tilemap_blocks.py

- Ignoring encoder when ' NOMAIN' is defined, since it is a time consuming process and not possible in a scene simulation
- The three files needed by `tilemap_blocks.py` are regenerated from the memory banks in `rest2bin.sh`
- `tilemap_blocks.py`  generates the compressed tilemap and reference needed for the simulation

riders: scene simulation working again in glfgreat

---

modules/jtframe/devops/build-dockers.sh
modules/jtframe/devops/jtcore-base.df
modules/jtframe/devops/jtcore13.df
modules/jtframe/devops/jtcore17.df
modules/jtframe/devops/jtcore20.df

This image has been modified to use Ubuntu 20.04 due to some compatibility issues with some i386 libraries.
For that purpose, it can no longer be based on `jtcore-base`, so it has to install all dependencies that `jtcore-base` used to do.

Fixed jtcore13 to use Ubuntu 20.04

---

modules/jtframe/bin/run_regression.sh

In the master version, if you use `run_regression.sh --help` the script will respond as if you are using too few arguments.
You would need to add more useless arguments to get it to print the help text. Changing the order, `print --help` works as it should

minor: Regression script print help

---

cores/riders/cfg/mem.yaml
cores/riders/hdl/jtriders_game.v
cores/riders/hdl/jtriders_psac.v
cores/riders/hdl/jtriders_video.v
cores/riders/ver/game/rest2bin.sh

I haven't used `unless: [ POCKET ]` in mem.yaml, since it should not be included  in the smaller FPGAs either and the Pocket's SRAM is not implemented in the core yet
Is it possible to use `unless: [ NOPSAC | POCKET ] ` in `mem.yaml`?

riders/glfgreat: psac compressed tilemap moved to BRAM

---

cores/thundr/hdl/jtthundr_colmix.v

thundr: delay priority with pxl. Fixes #1103
