jotego/jtcores

mist/hdl/jtgng_game.v
mist/hdl/jtgng_mist.v
mist/hdl/jtgng_timer.v
mist/hdl/osd.v

Had to update the OSD, too, it didn't work well on TV (and now it has only 1 clock).

Add 15kHz TV mode

---

1943/hdl/jt1943_mist.v

For those who don't have a rotatable stand for his monitor.

Rotate controls option

---

modules/jtgng_timer.v

VSync should be aligned to the rising edge of HSync
This fixes Direct video

Align VSync to HSync

---

cores/biocom/hdl/jtbiocom.def
cores/biocom/hdl/jtbiocom_main.v

Biocom: adjust CEN's to the MCU's needs

---

cores/biocom/hdl/jtbiocom.qip
cores/biocom/hdl/jtbiocom_sound.v

- use the same clock for the CPU as for FM
- don't use WAIT_N in the CPU
- use the CPU in JTFRAME

Biocom: fix sound + update jtframe

---

cores/sarms/hdl/jtsarms_game.v
cores/sarms/hdl/jtsarms_video.v

center analog video
video width to 384px
moved char layer right by 3px

Side arms: video fixes

---

cores/1942/hdl/jt1942_game.v
cores/1943/hdl/jt1943_game.v
cores/biocom/hdl/jtbiocom_sdram.v
cores/btiger/hdl/jtbtiger_game.v
cores/exed/hdl/jtexed_game.v
cores/gng/hdl/jtgng_game.v
cores/tora/ver/game/microrom.mem
cores/tora/ver/game/nanorom.mem

fixes issues #105,#103,#102,#101

sdram_req -> sdram_rd

---

cores/s16/hdl/jts16_scr.v

- Prevent an unexpected overlow on eff_hscr
- Use pxl_cen2 for linebuffer writes
Fixes SDI, no problem with Cotton title&attract mode. Also checked Golden Axe, still looks good.

S16: scroll layer fixes (#525)

---

.gitignore
modules/jtframe/src/jtframe/cfgstr/cfgstr.go
modules/jtframe/src/jtframe/cmd/cfgstr.go
modules/jtframe/src/jtframe/cmd/update.go
modules/jtframe/src/jtframe/def/def.go
modules/jtframe/target/mist/data_io.v
modules/jtframe/target/mist/i2c_master.v
modules/jtframe/target/mist/i2s.v
modules/jtframe/target/mist/jtframe_mist.sv
modules/jtframe/target/mist/jtframe_mist_base.v
modules/jtframe/target/mist/jtframe_mist_top.sv
modules/jtframe/target/mist/osd.sv
modules/jtframe/target/mist/spdif.v
modules/jtframe/target/mist/target.yaml
modules/jtframe/target/mist/user_io.v
modules/jtframe/target/sidi128/sidi128.qpf
modules/jtframe/target/sidi128/sidi128.qsf
modules/jtframe/target/sidi128/target.yaml

Not to merge (yet), just to run the tests.

Add SiDi128 target

---

modules/jtframe/bin/jotego_20.04.sh

I used the jotego_20.04.sh script after installing ubuntu 20.04 and encountered many errors. I have modified so it passes cleanly on my computer. If anyone else needs it, this is my version of it.

modified jotego_20.04.sh script

---

cores/toki/cfg/mame2mra.toml

Fixes #604 
Add missing MRA file

Fixes #604

---

modules/jtframe/bin/jt-crtcfg.py
modules/jtframe/target/mister/sys/yc_out.sv

Fixed issues in PAL and RGBS video options

Analogizer (Fix for PAL and RGBS)

---

cores/circus/cfg/mame2mra.toml

Button name based on arcade cabinet: http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=circusc&lang=en
Toya

circus: add button name

---

cores/cps1/hdl/jtcps1_colmix.v

-This fixes the fuel hoses priority bug in cawing. 
-Nemo heads animation is now only visible inside the Nemo letters 
-Lou's gun in 3wonders is now only visible inside square frame

cps1_colmix: adjust layer priority to fix cawing

---

cores/riders/hdl/jtriders_colmix.v

Still needs more testing in-game

Makes dimming visible in riders when JTFRAME_RELEASE is defined

---

modules/jtframe/hdl/ram/jtframe_ioctl_dump.v

...can be still asserted while it shouldn't, see #767

jtframe: don't delay the sel signal in ioctl_dump

---

cores/s18/cfg/mame2mra.toml

Fixed button names
https://www.gallopingghostarcade.com/wp-content/uploads/2017/04/17635187_10211219285910014_703433726872596026_o.jpg
https://gamesdb.launchbox-app.com/games/images/8407-michael-jacksons-moonwalker

s18: Corrected button names

---

cores/wc/hdl/jtwc_game.v
cores/wc/hdl/jtwc_sound.v

jtwc: main CPU can reset the sound CPU (#867)

---

README.md

Link the actual game list that now exists

Small update to Readme.MD 

---

cores/twin16/cfg/mame2mra.toml

Third button in twin16/cuebrick

---

modules/jtframe/hdl/video/rotate/unsigned_division.v

Fixed broken rotation in sidi128

---

.github/workflows/daily.yaml

This should fix Compilation with Quartus 13 too

No linter for compile_all (quartus13)

---

modules/jtframe/bin/jtcore

Yesterday fixed enabled back Mister compilation, but the compile_all still got stuck compiling for pocket
This should fix it

Fix for stuck compilation

---

cores/cop/cfg/mame2mra.toml
cores/ninja/cfg/mame2mra.toml
cores/pang/cfg/mame2mra.toml
cores/roc/cfg/mame2mra.toml
cores/slyspy/cfg/mame2mra.toml

Removed uses of name_sort and ext_sort

---

cores/gaiden/hdl/jtgaiden_video.v

gaiden: Moved VS for image fitting better in the screen

---

cores/kchamp/cfg/mame2mra.toml

Fixes #1018 by correcting the names of the assigned buttons

Swapped left-right button names for kchamp

---

modules/jt680x/ucode/6301.yaml
modules/jt680x/ucode/6801.yaml
modules/jt680x/ucode/680x.yaml

Fixes Compile All, by including missing instructions

Undoc instructions in 6801.yaml

---

cores/ngp/hdl/jtngp_vtimer.v

Tested in a couple of games and seems to fix #994

Fix for #994

---

modules/jtframe/hdl/jtframe_board.v
modules/jtframe/hdl/video/jtframe_credits.v
modules/jtframe/target/mist/hdl/jtframe_mist.sv
modules/jtframe/target/mister/hdl/jtframe_mister.sv

Fixes #994 
Wait for new commit in Pocket before merging

Delayed HS/VS with jtframe_credits

---

cores/riders/hdl/jtglfgreat_encoder.v
cores/riders/ver/game/rest2bin.sh
cores/riders/ver/glfgreat/tilemap_blocks.py

glfgreat: fixed psac tilemap encoding & typo

---

cores/karnov/hdl/jtkarnov_obj.v

Fixes #1199
In karnov, hdump ranges from 0~0FF and then 180~1FF, and invalid values are automatically corrected in `jtframe_objdraw_gate.v`.  Also, directly valid values (180~1FF) are exchanged for invalid ones (100~17F)
For the objects starting position an offset is substracted, leading to sometimes starting values that can be converted in the process. If an objects has to be drawn from positions 1F7 to 007, for example, positions 1F7~1FF are converted to 177~17F, so they are never read by hdump. 
the effective writing address cannot be changed mid saving, since the initial point is saved once and then goes in steps of +1 until done in `jtframe_draw.v`
This first commit introduces a change in how the obj_buffer is read by karnov when flip=1, so this _hidden_ positions can be found. The …

karnov obj: Fix for #1199
